---
 name: what it does install and config db
 hosts:
 become: yes
 
 vars:
    oracle_db_ports_value : 1521
    
 tasks:
 -name: install the oracle db
  yum: <Code to intsall>
 
  -name: Ensure installed is enabled and running


  service:
    name:<service name>  
 