version: "3"
services:
  nginx:
    image:nginx:stable-alphine
  node-app:
    build: .
    image: dockerkeerthi/node-app
    environment:
      - PORT=3000
    depends_on:
      - mongo  

      
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sanjeev
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo-db:/data/db
      
  redis:
    image: redis  
    
volumes:
  mongo-db: